global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "backend-blog-fiap"
    scrape_interval: 1s
    static_configs:
      - targets: ["backend-blog-fiap:5032"]