name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t $DOCKER_USERNAME/backend-blog-fiap:latest --build-arg PORT=${{secrets.PORT}} --build-arg HOST=${{secrets.HOST}} --build-arg NODE_ENV=${{secrets.NODE_ENV}} --build-arg DB_HOST=${{secrets.DB_HOST}} --build-arg DB_PORT=${{secrets.DB_PORT}} --build-arg DB_USER=${{secrets.DB_USER}} --build-arg DB_PASS=${{secrets.DB_PASS}} --build-arg DB_NAME=${{secrets.DB_NAME}} --build-arg JWT_SECRET=${{secrets.JWT_SECRET}} --build-arg NAME_USER_DEFAULT=${{secrets.NAME_USER_DEFAULT}} --build-arg EMAIL_USER_DEFAULT=${{secrets.EMAIL_USER_DEFAULT}} --build-arg SOBRENOME_USER_DEFAULT=${{secrets.SOBRENOME_USER_DEFAULT}} --build-arg SENHA_USER_DEFAULT=${{secrets.SENHA_USER_DEFAULT}} --build-arg SALVAR_FOTO_LOCAL=${{secrets.SALVAR_FOTO_LOCAL}} --build-arg URL=${{secrets.URL}} --build-arg GOOGLE_HOST=${{secrets.GOOGLE_HOST}} --build-arg GOOGLE_PORT=${{secrets.GOOGLE_PORT}} --build-arg MAIL_USERNAME=${{secrets.MAIL_USERNAME}} --build-arg MAIL_PASSWORD=${{secrets.MAIL_PASSWORD}} --build-arg REGRAS_PERMISSOES=${{'secrets.REGRAS_PERMISSOES'}} .
          docker push $DOCKER_USERNAME/backend-blog-fiap:latest
 